apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearning-monitor
spec:
  replicas: 2  # Rendu pod odum, High Availability-ku
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor-app
        image: e-learning-monitor  # Neenga build panna adhe peru
        imagePullPolicy: Never      # External cloud-la irundhu pull pannaama local-aa edukkum