apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearning-monitor-deployment
spec:
  replicas: 2 # Rendu container eppovum odum (High Availability)
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor-app
        image: e-learning-monitor # Unga Docker image peru
        imagePullPolicy: Never # Minikube local image-ahye eduthu paarkkum